if (typeof langProxy === 'undefined') {
    langProxy = {};
}
langProxy['de'] = {
    icon: '🇩🇪',
    name: 'german',
    // Language
    german: 'Deutsch',
    english: 'Englisch',
    // UI
    title: 'Strickmuster-Planer',
    about: 'Über diese Software',
    configure: 'Muster ändern',
    start: 'Stricken starten',
    prev: 'Vorherige Reihe',
    next: 'Nächste Reihe',
    rows: 'Reihen',
    stitches: 'Maschen',
    totalLength: 'Gesamtlänge',
    totalLengthDescription: 'Wie lang soll der Schal von Spitze bis Spitze entlang seiner längsten Dimension sein?',
    centerLength: 'Mittellänge',
    centerLengthDescription: 'Wie viele zusätzliche Reihen soll der Schal im Mittelteil (zwischen Zunahmen und Abnahmen) entlang der langen Dimension haben?',
    centerWidth: 'Mittelbreite',
    centerWidthDescription: 'Wie viele Maschen soll der Schal im Mittelteil, zwischen den Zunahmen und Abnahmen, haben (Breite des Schals)? Enthält nicht die 6 Maschen für den i-cord Rand.',
    texture: 'Textur',
    textureDescription: 'Welche Art von Textur möchtest du?',
    shape: 'Form',
    shapeDescription: 'Welche allgemeine Form möchtest du?',
    inputs: 'Eingaben',
    outputs: 'Ausgaben',
    // Patterns
    garter: 'Kraus rechts',
    doubleMoss: 'Perlmuster',
    // Shapes
    balanced: 'Ausgeglichen',
    thin: 'Dünn',
    thick: 'Dick',
    straight: 'Dreieck',
    // Stitches
    stitchKnit: 'R',
    stitchKnitDescription: 'Rechts',
    stitchPurl: 'L',
    stitchPurlDescription: 'Links',
    stitchKnitFrontBack: 'RZ',
    stitchKnitFrontBackDescription: 'Rechts zunehmen',
    stitchSlipStitchPurlwise: 'A',
    stitchSlipStitchPurlwiseDescription: 'Abheben',
    stitchKnitTwoTogether: '2RzZ',
    stitchKnitTwoTogetherDescription: 'Zwei rechte Maschen zusammenstricken',
    stitchWithYarnInFront: 'F',
    stitchWithYarnInFrontDescription: 'Faden vor die Arbeit legen',
    // Errors
    lessOrEqual: '%1 (%2) muss kleiner oder gleich %3 (%4) sein',
    nanOutputs: 'Ausgaben müssen eine Zahl sein',
    nanRepetitions: 'Wiederholungen müssen eine Zahl sein',
    constantsUndefined: 'Konstante %1 ist nicht definiert.',
    invalidBezierParameter: 'Ungültiger Zeitpunkt %1 für Bezier-Kurve',
    invalidIndex: 'Ungültiger Index %1 für Bezier-Array (Größe: %2)',
    invalidIndexN: 'Ungültiger Index n = %1 für Bezier-Array',
    emptyLastRow: 'Versuch, die letzte Reihe eines leeren Musters abzurufen',
};
